# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Ioka' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'Ioka', :path => '/Users/ablaierzhanov/Desktop/ioka-ios'

end
