# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IokaDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod "CreditCardValidator", '~> 0.5.3'
   pod 'Ioka', :path => '..'
   
end
